In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading Train dataset

In [2]:
data=pd.read_csv(r'C:\ANISHA\train_ctrUa4K.csv')
data

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

# Top 5 rows

In [3]:
data.head(5)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

# Last 5 rows

In [4]:
data.tail(5)

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [5]:
data.shape

(614, 13)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [7]:
data.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [8]:
data.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# Handling Missing Values

In [9]:
data=data.drop('Loan_ID',axis=1)

In [10]:
data.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [11]:
columns=['Gender', 'Dependents','LoanAmount','Loan_Amount_Term']
data=data.dropna(subset=columns)

In [12]:
data.isna().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        30
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       48
Property_Area         0
Loan_Status           0
dtype: int64

In [13]:
data['Self_Employed'].mode()[0]

'No'

In [14]:
data['Self_Employed']=data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])

In [15]:
data.isna().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       48
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
data['Credit_History'].unique()

array([ 1.,  0., nan])

In [17]:
data['Credit_History'].mode()[0]

1.0

In [18]:
data['Credit_History']=data['Credit_History'].fillna(data['Credit_History'].mode()[0])

In [19]:
data.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Handling Categorical columns

In [21]:
data.sample(5)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
567    Male     Yes         3+  Graduate            No             3400   
146  Female     Yes          2  Graduate            No            14866   
381    Male      No          0  Graduate            No             5941   
51   Female      No          0  Graduate            No             3086   
348    Male     Yes          0  Graduate            No             6333   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
567             2500.0       123.0             360.0             0.0   
146                0.0        70.0             360.0             1.0   
381             4232.0       296.0             360.0             1.0   
51                 0.0       120.0             360.0             1.0   
348             4583.0       259.0             360.0             1.0   

    Property_Area Loan_Status  
567         Rural           N  
146         Urban           Y  
381     Semiurban           Y  
51      Semiurban           Y  
348     Semiurban           Y

In [22]:
data['Dependents'].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [23]:
data['Dependents']=data['Dependents'].replace(to_replace="3+",value="4")

In [24]:
data['Dependents'].unique()

array(['1', '0', '2', '4'], dtype=object)

# Categorical columns into numerical 

In [25]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [27]:
data['Gender']=le.fit_transform(data['Gender'])
data['Gender'].unique()

array([1, 0])

In [28]:
data['Married'].unique()

array(['Yes', 'No'], dtype=object)

In [29]:
data['Married']=le.fit_transform(data['Married'])
data['Married'].unique()

array([1, 0])

In [30]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [31]:
data['Education']=le.fit_transform(data['Education'])
data['Education'].unique()

array([0, 1])

In [32]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [33]:
data['Self_Employed']=le.fit_transform(data['Self_Employed'])
data['Self_Employed'].unique()

array([0, 1])

In [34]:
data['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [35]:
data['Property_Area']=le.fit_transform(data['Property_Area'])
data['Property_Area'].unique()

array([0, 2, 1])

In [36]:
data['Loan_Status'].unique()

array(['N', 'Y'], dtype=object)

In [37]:
#data['Loan_Status']=le.fit_transform(data['Loan_Status'])
#data['Loan_Status'].unique()

In [38]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1          1          0              0             4583   
2       1        1          0          0              1             3000   
3       1        1          0          1              0             2583   
4       1        0          0          0              0             6000   
5       1        1          2          0              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area Loan_Status  
1              0           N  
2              2           Y  
3              2           Y  
4              2           Y  
5              2           Y

# spliting of data

In [39]:
y=data['Loan_Status']
x=data.drop(['Loan_Status'],axis=1)

In [40]:
y

1      N
2      Y
3      Y
4      Y
5      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 553, dtype: object

# Feature Scaling

In [41]:
cols=['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']

In [42]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x[cols]=st.fit_transform(x[cols])

In [43]:
x

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          0              0        -0.128694   
2         1        1          0          0              1        -0.394296   
3         1        1          0          1              0        -0.464262   
4         1        0          0          0              0         0.109057   
5         1        1          2          0              1         0.011239   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          0              0        -0.411075   
610       1        1          4          0              0        -0.208727   
611       1        1          1          0              0         0.456706   
612       1        1          2          0              0         0.374659   
613       0        0          0          0              1        -0.128694   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1            -0.049699   -0.214368          0.279961             1.0   
2            -0.545638   -0.952675          0.279961             1.0   
3             0.229842   -0.309634          0.279961             1.0   
4            -0.545638   -0.059562          0.279961             1.0   
5             0.834309    1.440866          0.279961             1.0   
..                 ...         ...               ...             ...   
609          -0.545638   -0.893134          0.279961             1.0   
610          -0.545638   -1.262287         -2.468292             1.0   
611          -0.466709    1.274152          0.279961             1.0   
612          -0.545638    0.488213          0.279961             1.0   
613          -0.545638   -0.154828          0.279961             0.0   

     Property_Area  
1                0  
2                2  
3                2  
4                2  
5                2  
..             ...  
609              0  
610              0  
611              2  
612              2  
613              1  

[553 rows x 11 columns]

# K-Fold Cross validation

In [44]:
from sklearn.model_selection import train_test_split


In [45]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [46]:
model_df={}
def model_val(model,x,y):
    x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f"{model}accuracy is{accuracy_score(y_test,y_pred)}")
    score=cross_val_score(model,x,y,cv=5)
    print(f"{model}average cross val score is{np.mean(score)}")
    model_df[model]=round(np.mean(score)*100,2)

In [47]:
model_df

{}

# Logistic Regression 

In [48]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model_val(model,x,y)


LogisticRegression()accuracy is0.7927927927927928
LogisticRegression()average cross val score is0.802964782964783


# SVC

In [49]:
from sklearn.svm import SVC
model=SVC(kernel='linear')
model_val(model,x,y)

SVC(kernel='linear')accuracy is0.8018018018018018
SVC(kernel='linear')average cross val score is0.8066011466011467


# Decision Tree

In [50]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(random_state=42)
model_val(model,x,y)

DecisionTreeClassifier(random_state=42)accuracy is0.7477477477477478
DecisionTreeClassifier(random_state=42)average cross val score is0.7033906633906634


# Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model_val(model,x,y)

RandomForestClassifier(n_estimators=50)accuracy is0.7927927927927928
RandomForestClassifier(n_estimators=50)average cross val score is0.784864864864865


# Hyperparameter Tuning for Logistic Regression

In [52]:
from sklearn.model_selection import RandomizedSearchCV

In [53]:
log_reg_grid={"C":np.logspace(-4,4,20),"solver":['liblinear']}

In [54]:
rs_log_reg=RandomizedSearchCV(LogisticRegression(),param_distributions=log_reg_grid,n_iter=20,cv=5,verbose=True)

In [55]:
rs_log_reg.fit(x,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [56]:
rs_log_reg.best_score_

0.802964782964783

In [57]:
rs_log_reg.best_params_

{'solver': 'liblinear', 'C': 0.23357214690901212}

# Hyperparameter Tuning for SVM

In [58]:
svc_grid={'C':[0,25,0.50,0.75,1],"kernel":["linear"]}
rs_svc=RandomizedSearchCV(SVC(),param_distributions=svc_grid,n_iter=20,cv=5,verbose=True)

In [59]:
rs_svc.fit(x,y)

C:\Users\anish\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:292: UserWarning: The total space of parameters 5 is smaller than n_iter=20. Running 5 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Fitting 5 folds for each of 5 candidates, totalling 25 fits


C:\Users\anish\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 25.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\anish\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\anish\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\Users\anish\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn\svm\_libsvm.pyx", l

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=20,
                   param_distributions={'C': [0, 25, 0.5, 0.75, 1],
                                        'kernel': ['linear']},
                   verbose=True)

In [60]:
rs_svc.best_score_

0.8066011466011467

In [61]:
rs_svc.best_params_

{'kernel': 'linear', 'C': 25}

# Hyperparameter Tuning for Random forest

In [62]:
RandomForestClassifier()

RandomForestClassifier()

In [63]:
rf_grid={'n_estimators':np.arange(10,1000,10),'max_features':['auto','sqrt'],'max_depth':[None,3,5,10,20,30],'min_samples_split':[2,5,20,50,100],'min_samples_leaf':[1,2,5,10]}

In [64]:
rs_rf=RandomizedSearchCV(RandomForestClassifier(),param_distributions=rf_grid,n_iter=20,cv=5,verbose=True)

In [65]:
rs_rf.fit(x,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_depth': [None, 3, 5, 10, 20, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 20, 50,
                                                              100],
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 9

In [66]:
rs_rf.best_score_

0.8066175266175266

In [67]:
rs_rf.best_params_

{'n_estimators': 440,
 'min_samples_split': 50,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': None}

# Model-Random-Forest

In [68]:
y=data['Loan_Status']
x=data.drop(['Loan_Status'],axis=1)

In [69]:
rf=RandomForestClassifier(n_estimators=220,
 min_samples_split=100,
 min_samples_leaf=2,
 max_features='auto',
 max_depth=10)

In [70]:
rf.fit(x,y)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=100,
                       n_estimators=220)

In [71]:
import joblib

In [72]:
joblib.dump(rf,'loan_status_predict')

['loan_status_predict']

In [73]:
model=joblib.load('loan_status_predict')

# prediction

In [74]:
data

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          0              0             4583   
2         1        1          0          0              1             3000   
3         1        1          0          1              0             2583   
4         1        0          0          0              0             6000   
5         1        1          2          0              1             5417   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          0              0             2900   
610       1        1          4          0              0             4106   
611       1        1          1          0              0             8072   
612       1        1          2          0              0             7583   
613       0        0          0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area Loan_Status  
1                0           N  
2                2           Y  
3                2           Y  
4                2           Y  
5                2           Y  
..             ...         ...  
609              0           Y  
610              0           Y  
611              2           Y  
612              2           Y  
613              1           N  

[553 rows x 12 columns]

In [75]:
df=pd.DataFrame({
    'Gender':1,
    'Married':0,
    'Dependents':2,
    'Education':0,
    'Self_Employed':0,
    'ApplicantIncome':2500,
    'CoapplicantIncome':4500,
    'LoanAmount':120,
    'Loan_Amount_Term':180,
    'Credit_History':1,
    'Property_Area':1},index=[0])

In [76]:
df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           2          0              0             2500   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0               4500         120               180               1   

   Property_Area  
0              1

In [77]:
result=model.predict(df)

In [78]:
if result==1:
    print("loan approved")
else:
    print("loan not approved")

loan not approved


In [83]:
y

1      N
2      Y
3      Y
4      Y
5      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 553, dtype: category
Categories (2, object): ['N', 'Y']

In [84]:
for name in y:
    print(name)

N
Y
Y
Y
Y
Y
N
Y
N
Y
Y
Y
N
Y
Y
Y
N
N
N
Y
N
N
Y
Y
Y
N
Y
N
N
N
Y
N
Y
Y
Y
N
Y
Y
Y
Y
Y
N
Y
Y
Y
N
N
N
Y
Y
N
Y
Y
Y
Y
N
N
N
N
Y
Y
N
Y
Y
Y
Y
N
N
N
N
Y
Y
N
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
N
Y
Y
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
Y
N
N
Y
Y
Y
Y
Y
N
N
Y
N
N
N
Y
Y
Y
Y
Y
Y
Y
N
Y
N
Y
N
N
Y
Y
Y
Y
Y
Y
Y
N
N
Y
Y
N
Y
N
Y
Y
N
Y
N
Y
Y
N
Y
N
N
N
Y
N
Y
Y
N
Y
Y
Y
N
N
Y
Y
N
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
Y
N
N
N
Y
Y
Y
Y
N
Y
N
Y
N
Y
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
N
Y
Y
Y
Y
N
N
Y
Y
N
Y
N
N
N
N
Y
Y
N
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
N
N
N
Y
Y
Y
Y
N
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
N
N
Y
Y
Y
Y
Y
Y
Y
Y
N
Y
N
Y
Y
N
N
Y
N
Y
Y
Y
Y
N
N
Y
N
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
Y
Y
N
N
N
Y
Y
N
Y
Y
Y
N
N
N
Y
N
Y
N
Y
N
N
Y
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
Y
Y
Y
Y
N
N
N
N
Y
N
Y
Y
Y
Y
N
Y
N
Y
Y
Y
N
Y
N
Y
N
Y
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
N
Y
N
Y
Y
Y
Y
N
Y
Y
Y
Y
N
Y
Y
Y
N
Y
Y
Y
Y
Y
N
Y
Y
N
N
Y
Y
N
N
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
N
N
Y
Y
Y
Y
N
Y
Y
N
Y
Y
Y
Y
N
Y
N
Y
Y
N
N


1      N
2      Y
3      Y
4      Y
5      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 553, dtype: object

1      N
2      Y
3      Y
4      Y
5      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 553, dtype: category
Categories (2, object): ['N', 'Y']